import photo1 from "/mumlava.webp"

const data = [
    {
        id: 1,
        title: "Mumlavské vodopády",
        tags: "🚲 🎒 📷",
        perex: "Dravá řeka Mumlava vytváří poblíž Harrachova, v Mumlavském dole, vodopád tvořený stupňovitými žulovými bloky. Asi 10 m vysoký skalní stupeň v žulovém řečišti se nachází nedaleko centra Harrachova v západní části Mumlavského dolu.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",
        photo: photo1,
        alt: "mumlava",
       
    },
    {
        id: 2,
        title: "Muzeum skla Harrachov",
        tags: " 📷 🥪",
        perex: " Muzeum skla je součástí sklárny v Harrachově. Obsahuje historicky a technologicky ucelenou sbírku historického skla z produkce harrachovské sklárny.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",
        
    },
    {
        id: 3,
        title: "IQLandia",
        tags: " 📷 🥪",
        perex: "iQLANDIA je vhodná pro děti od 8 let a všechny dospělé. Exponáty jsou techničtější, popisy odbornější, doprovodné programy (workshopy, science show) vysvětlují jevy, o kterých už děti někdy slyšely ve škole.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",

    },

    {
        id: 4,
        title: "Prachovské skály",
        tags: " 📷 🥪 🧗🚶‍♀️👨‍👩‍👧‍👦",
        perex: "Prachovské skály tvoří pískovcové skalní město. Díky otevřeným náhorním plošinám je zde nespočet vyhlídek, z nichž budete mít celý Český ráj jako na dlani.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",

    },
    {
        id: 5,
        title: "Teplické skály",
        tags: " 📷 🥪 🧗🚶‍♀️👨‍👩‍👧‍👦",
        perex: "Teplické skalní město odděluje od toho Adršpašského 4 kilometry dlouhá Vlčí rokle. Teplické skály jsou rozsáhlejší částí Národní přírodní rezervace Adršpašsko-teplické skály. Jsou známé divokým skalním labyrintem, svými vysokými skalními útvary, rozsáhlými masivy a pohádkovou přírodou.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",

    },
    {
        id: 6,
        title: "Babiččino údolí",
        tags: " 📷 🥪 🚶‍♀️👨‍👩‍👧‍👦",
        perex: "Babiččino údolí je turisticky navštěvováno zejména kvůli spisovatelce Boženě Němcové, která zde zasadila děj díla Babička Ale díky značně členitému terénu, který vytváří prostor pro pestrost květeny i výskyt mnoha zajímavých i vzácných živočichů, je i cennou přírodní lokalitou.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",

    },
    {
        id: 7,
        title: "Zámek Ratibořice",
        tags: " 📷 🚶‍♀️👨‍👩‍👧‍👦",
        perex: "Zámek byl založen na počátku osmnáctého století jako letní lovecké sídlo Lorenza Piccolominiho. Dochovaná podoba je výsledkem rozsáhlých úprav provedených po roce 1800 v klasicistním a empírovém stylu.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",

    },
    {
        id: 8,
        title: "Zámek Hrádek u Nechanic",
        tags: " 📷 🥪 👨‍👩‍👧‍👦",
        perex: "Hrádek u Nechanic je neogotický zámecký objekt ležící na mírné vyvýšenině 800 m severozápadně od centra vsi Hrádek, 2,8 km jihovýchodně od města Nechanice a 11,5 km západně od Hradce Králové v okrese Hradec Králové.",
        description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Aenean vel massa quis mauris vehicula lacinia. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla non arcu lacinia neque faucibus fringilla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum facilisis augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Nulla quis diam. Vivamus porttitor turpis ac leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis magna eu sem. Nulla quis diam. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis pulvinar. Mauris metus. Aliquam id dolor. Duis pulvinar. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Maecenas aliquet accumsan leo. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam at arcu a est sollicitudin euismod. Nunc tincidunt ante vitae massa. Nulla est. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam rhoncus aliquam metus. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula. Nunc dapibus tortor vel mi dapibus sollicitudin. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris dictum facilisis augue. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Aliquam ornare wisi eu metus. Aenean fermentum risus id tortor.",

    },
    
]

export default data